apiVersion: 1

datasources:
  - name: LokLingo Prometheus
    uid: loklingo-prometheus
    type: prometheus
    access: proxy
    url: http://loklingo-prometheus:9090
    isDefault: true
    editable: false
